import type { Metadata } from "next";
import localfont from "next/font/local";
import "./globals.css";
import Navbar from "@/app/layout/Navbar";
import Footer from "@/app/layout/Footer";


const scientifica = localfont({
  src: [
    {
      path: "./fonts/scientifica.ttf",
      weight: "400",
      style: "normal"
    },
    {
      path: "./fonts/scientificaBold.ttf",
      weight: "800",
      style: "bold"
    },
    {
      path: "./fonts/scientificaItalic.ttf",
      weight: "400",
      style: "italic"
    },
  ]
})

export const metadata: Metadata = {
  title: "THS Computer Science",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${scientifica.className} bg-background antialiased`}
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
