import Officer from "@/util/Officers/Officer";
import Scroll from "@/util/Scroll";


export default function Officers()
{
    return (
        <Scroll className="flex flex-col items-center mt-10">
            <h1 className="shadow_class text-6xl">Officers</h1>        
            <div className="mt-10 flex flex-wrap justify-center gap-5">
                <Officer name="Jaiden Khosla" role="President" background="bg-blue-400" description={"I've always been interested in STEM, particularly computer science and mathematics. Some of my passions are teaching, listening to music, watching sitcoms, and coding any wonky ideas that come to mind. Currently, I'm listening to Radiohead, Primus, and My Blood Valentine. In my opinion, the best sitcom of all time is either Srubs or Community. (Fun fact: I coded this website)"} github="https://github.com/JaidenKhosla" instagram="https://www.instagram.com/jaidenkhosla" image="/assets/officers/JaidenKhosla.jpg"/>
                <Officer name="David Liu" role="Vice President" description={"I have large dreams of making society better by combining music with artificial intelligence.I am very effective at achieving my goals because I believe that both efficiency and hard work contribute to solving hard problems. I always think about whether there is a faster and more effective way to get the grade or win a competition. My hobbies include coding, playing the violin, playing tennis. My favorite algorithm is KMP and my favorite line of code is auto result = std::reduce(v.begin(), v.end());"} image="/assets/officers/DavidLiu.jpg"/>
                <Officer name="Arden Hatchett" role="Treasurer" background="bg-green-200" description={"I don't really know what I want to put effort in, my favorite hobby is walking, and I get some song stuck in my head for weeks rather than liking artists. Before you say it, no, I do not like drinking water, breathing, or eating... unless it's a good meat, rice, or noodles. I just enjoy spending time with the right people and talking about the right topics. My school interests as a Junior are computer science, which, now you know my role, and debate, which I am now quite a young president of. I'll probably pursue something in law or computers, and a lot of people tell me to go into law or politics, but, for now, I'm stuck reading the news and yelling at the screen at the wrong idiots who run the world."} image="/assets/officers/ArdenHatchett.jpg"/>
                <Officer name="Advik Singh" role="Social Media Manager" background="bg-yellow-100" description={"My hobbies include music, singing and playing guitar, and cars. I also dabble in programming and robotics as well. I am interested in pursuing an Electrical Engineering pathway. My favorite car is the NA Miata, and my (probably achievable) dream car, down the line, is a 2010 Porsche 718 Cayman S. My favorite artists are Frank Ocean, Mac Miller, and Brent Faiyaz. My favorite TV show has to be Night Agent."} github="https://github.com/advik-cookies" instagram="https://www.instagram.com/advik_cookies" image="/assets/officers/AdvikSingh.jpg"/>
                <Officer name="Ranveer Sohal" role="Social Media Manager" background="bg-teal-300" description={"I really like exploring the outdoors, playing video games and the piano, hanging out with friends and listening to music. I am not the greatest at computer science, but I think I make up for that in my skills in many other fields. My favorite music artists are probably DM DORUKO, Toby Fox, and Heaven Pierce Her (I like a lot of video game OST's). Some games I really like are ULTRAKILL, Undertale, Terraria, Risk of Rain 2, and BTD6, just to name a few. One saying I believe and if given the chance to send the message to the whole world, would be “What you like and do doesn’t matter to me, as long as you aren’t hurting yourself or others.”"} image="/assets/officers/RanveerSohal.jpg"/>
                <Officer name="Oliver Fan" role="Technical Manager" background="bg-blue-300" description={"Greetings! I’m Oliver. In addition to serving as a CS Club officer, I’m also the president of AI Club. I’m interested in AI, programming, math, physics, and space exploration. As a very curious person, I am, fortunately or unfortunately, never satisfied with surface-level answers. I always like to dive deeper and often ask questions that even my teachers struggle to answer. I aspire to pursue a career in Aerospace or Electrical Engineering, and my biggest dream is to one day go to space on a rocket that I helped build. Beyond my academic interests, I enjoy playing the violin, reading books, and playing Minecraft. I love noodles, especially Pho, which is my absolute favorite. Thanks to Arden, I’ve also gotten more into politics and current events. My favorite animal is the octopus, and yes, I will be severely disappointed if you use the grammatically incorrect plural “octopi.”"} image="/assets/officers/OliverFan.jpg"/>
                <Officer name="Robert Lee Tompkins III" role="Technical Manager" background="bg-green-300" description={"I have always been interested in computer science ever since I was a wee lad. I aspire to pursue a career in cybersecurity. I know Java and a bit of C++ as well. I enjoy trying different foods. Currently, my favorite delicacy is foie gras, my favorite fish is halibut, and my favorite desert is crème brûlée 🍮. I don’t have very many hobbies, but some sports I enjoy are skeet shooting, shuffleboard, and frisbee golf. (I’m not great at any of the three but I enjoy them nevertheless.) My top 5 favorite movies/movie series are Blazing Saddles, Indiana Jones, Pirates of the Caribbean, Crocodile Dundee, and Star Wars."} image="/assets/officers/RobertTompkins.jpg"/>
                <Officer name="Shivani Olson" role="CSHS Manager" background="bg-[#F88379]" description={"I'm curious about various aspects of modern computing and their application to tackle the big problems. I like to help others grasp concepts in math and programming. In turn, this also improves my own understanding in a feedback loop!  I enjoy solving puzzles, playing the piano (esp. Debussy) and creating intricate crochet patterns. I enjoy reading mysteries and recently discovered a love for 19th century classics. My music taste is diverse, with my current obsessions being Laufey and Madonna."} image="/assets/officers/ShivaniOlson.jpg"/>
                <Officer name="Nikhil Khosla" role="AIM Manager" background="bg-yellow-200" description={"Some of my hobbies include programming, volunteering, and cooking. Along with that, I also really enjoy rock climbing and playing tennis. In the future, I plan on pursuing medicine, specifically in the health-technology field. Along with Computer Science Club, I participate heavily in Key Club and HOSA, as they are very aligned with my passions. As of now, my favorite TV shows are The Walking Dead, Invincible, and The Boys. I look forward to teaching and getting others engaged in the world of computer science in this upcoming year!"} image="/assets/officers/NikhilKhosla.jpg"/>

            </div>
        </Scroll>
    )
}